# config file for automatic testing at travis-ci.org
language: python

python:
    - "2.7"

install:
    # Install coveralls
    - pip install coveralls
    # install package + executables
    - pip install --editable .

script:
    # command to run tests and collect test coverage
    - py.test --cov-report html --cov checkit tests/tests.py

notifications:
    email: false

after_success:
    coveralls
